package redhat.brmsworkshop.lab1;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "Premium")
public class Premium  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Premium Amount")
    @org.kie.api.definition.type.Position(value = 1)
    private java.math.BigDecimal amount;
    
    @org.kie.api.definition.type.Label(value = "Premium Type")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String type;

    public Premium() {
    }

    public Premium(java.lang.String type, java.math.BigDecimal amount) {
        this.type = type;
        this.amount = amount;
    }


    
    public java.math.BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(  java.math.BigDecimal amount ) {
        this.amount = amount;
    }
    
    public java.lang.String getType() {
        return this.type;
    }

    public void setType(  java.lang.String type ) {
        this.type = type;
    }
}