package redhat.brmsworkshop.lab1;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "Violation Info")
public class Violation  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Violation Code")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String code;
    
    @org.kie.api.definition.type.Label(value = "Violation Description")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String description;

    public Violation() {
    }

    public Violation(java.lang.String code, java.lang.String description) {
        this.code = code;
        this.description = description;
    }


    
    public java.lang.String getCode() {
        return this.code;
    }

    public void setCode(  java.lang.String code ) {
        this.code = code;
    }
    
    public java.lang.String getDescription() {
        return this.description;
    }

    public void setDescription(  java.lang.String description ) {
        this.description = description;
    }
}